import { Unbounded } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const unbounded = Unbounded({ subsets: ["latin"] });

export const metadata = {
  title: "SoulChain🔗",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={unbounded.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
